receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
      - job_name: "node-exporter"
        scrape_interval: 5s
        static_configs:
          - targets: ["node-exporter:9100"]
            labels:
              app: "my-app"

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true

processors:
  batch:
    timeout: 5s
    send_batch_size: 512
    send_batch_max_size: 1024

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]  # Métricas enviadas a Prometheus
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]  # Trazas enviadas a Tempo
