apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"TraceID":"([A-Za-z0-9]+)"'
          name: "TraceID"
          url: $${__value.raw}
      maxLines: 1000
      loki_explore_enabled: true

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        tags: [ 'traceID', 'job' ]
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
      nodeGraph:
        enabled: true

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
